"""Initial migration

Revision ID: baf1a1d80610
Revises: 
Create Date: 2024-11-26 00:46:09.288678

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "baf1a1d80610"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
